### ISSUE TITLE
Signin not working for Android

### ISSUE THREAD

**Issue by bigyank** [K9i-0/flutter_tiktok_sdk#11]
It works on IOS perfectly but on Android login doesn't return anything. It does open a prompt for login and after the successful login, nothing happens.

Here is my [AndroidManifest.xml file](https://pastebin.com/rNUfjaVi)

**Comment by darshdobariya** [comment]
Can i help you ?

**Comment by K9i-0** [comment]
Try the following
```
<activity
           android:name=".tiktokapi.TikTokEntryActivity"
           android:exported="true">
```
replace
```
      <activity
          android:name="com.k9i.flutter_tiktok_sdk.TikTokEntryActivity"
          android:exported="true" />
```
