### ISSUE TITLE
 Failed to validate the certificate chain on WebView

### ISSUE THREAD

**Issue by bigyank** [K9i-0/flutter_tiktok_sdk#12]
Log: https://pastebin.com/dkKi86WS

I can not login in Android because of this error.
IOS works very well.

It works well on the Android Emulator and only fails on the real device

**Comment by K9i-0** [comment]
It may be an issue with TikTok's Android SDK.
Contact tiktok and they may know what it is.

https://developers.tiktok.com/doc/getting-started-faq/

**Comment by bigyank** [comment]
Thank you!! I'll reach out to them too

**Comment by bigyank** [comment]
It turns out my package name on the tiktok developers dashboard was wrong.
