### ISSUE TITLE
TikTokPermissionType user info stats does not have scope 

### ISSUE THREAD

**Issue by donzkie-dev** [K9i-0/flutter_tiktok_sdk#16]
Hi I'm trying to retrieve the scope for user.info.stats does not implemented to get the users followers count. Is there any way or any update on the sdk?

**Comment by K9i-0** [comment]
Starting from 0.2.6, user.info.stats is now available, so I will close this issue.
https://github.com/K9i-0/flutter_tiktok_sdk/pull/18
